kind: pipeline
type: kubernetes
name: build
when:
  event: push
  branch: master
steps:
  - name: docker
    image: plugins/gcr
    settings:
      repo: gcr.io/leoandco/namespacenodeselector
      tags:
        - latest
        - ${DRONE_COMMIT}
      json_key:
        from_secret: gcr

---
kind: secret
name: gcr
get:
  path: drone-gcr-secret
  name: apikey
