apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespacenodeselector
  namespace: namespacenodeselector
spec:
  selector:
    matchLabels:
      app: namespacenodeselector
  template:
    metadata:
      labels:
        app: namespacenodeselector
    spec:
      serviceAccountName: namespacenodeselector
      containers:
        - name: namespacenodeselector
          image: gcr.io/leoandco/namespacenodeselector:f69150b3d0dba043bac7ee8c12da8a127350607b
          env:
            - name: NSNS_CERTPATH
              value: /tls/cert
            - name: NSNS_KEYPATH
              value: /tls/key
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: tls
              mountPath: /tls
      volumes:
        - name: tls
          secret:
            secretName: namespacenodeselector

