apiVersion: v1
kind: Secret
metadata:
  name: namespacenodeselector
  namespace: namespacenodeselector
stringData:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIEQzCCAqugAwIBAgIRAMgRimGVZxs3F9rtlQ1xdBwwDQYJKoZIhvcNAQELBQAw
    XzEeMBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMRowGAYDVQQLDBFyb290
    QGE0ZmFjM2ZhOTFhZDEhMB8GA1UEAwwYbWtjZXJ0IHJvb3RAYTRmYWMzZmE5MWFk
    MB4XDTE5MDYwMTAwMDAwMFoXDTI5MTIxODEwNTExNFowRTEnMCUGA1UEChMebWtj
    ZXJ0IGRldmVsb3BtZW50IGNlcnRpZmljYXRlMRowGAYDVQQLDBFyb290QGE0ZmFj
    M2ZhOTFhZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKqSUteI/HHU
    8xX7xdOPjikmv7Ecs1JXtG8OYNu3RjvVXQVUQzk9eKrmNvm+O/R0WB3ul7Aa98qZ
    JupPIDjt74QOZ5bTo8QbDyBzIavRL/ukGgu2WuJ5eI37Rpvh9QfbRTNiSOR7v1/h
    ho6WuRhlKTbNRwXXIYsBUSK80LzEvm7ch3u5aGYehA3Khhs4Ed6F0noPB4kTmtGX
    WDl8S0eII8B4b0kDt5no+u4AFC74QGq0JrpPKQQDuTUIH528oGpx1Btf2MnRyzEV
    JAx0UTz4DiZibSQzilhFMgRowbxRPLmMLFrAHP4RlB4wDsVE6463tRqXZabu/7Le
    zudHuVpKTasCAwEAAaOBkzCBkDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYI
    KwYBBQUHAwEwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBTUC/bLECXuhWKQauYe
    Zog38vEMWDA6BgNVHREEMzAxgi9uYW1lc3BhY2Vub2Rlc2VsZWN0b3IubmFtZXNw
    YWNlbm9kZXNlbGVjdG9yLnN2YzANBgkqhkiG9w0BAQsFAAOCAYEA1EiylsZdZRYd
    PQXzzIz9ei9q3zmMoHpfTj8XTmdDj0tbYCh+GfgT1yKo8BNhptThjM/ZDeqIhgG1
    HrZ4a/igv/YcVs81ndtKgEAJhujW7s6+gekzCw+CuwSzGR716xKyZBdXSnrj5zLk
    b3zwrwk0kyfrDmLEkVvo6ItesJGorkTU+1O9tteZYveGV3nij6KESh9irlVIJqfH
    QmCuPC7Wu4+lnAWKC4N4cgFmr2zJQGQrWMBy2bO8vIpHXm69FtF66yiRs0IwILn3
    FEgOkjRM74AjR9mEOu7if8wyGEFSnDNrIqlSZZSjCz8GlvKzRqDIO4aFnEEZmaRi
    NTFbabJkdIPy3PSB41QaZMHq6JgvG4kWoS1Ont+qe3aXTM165hs4iRE3ct5cquUm
    in+d+zWM1dGae0BfU3MAvonqcqgV8sKIRM8atG6e58CKa8O2/5s+Vizp8/ICge+c
    uuAYmRrOyODP3YIoz65uGwegcTMV63wyalfZv5kM5pkFGt3XUmwj
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqklLXiPxx1PMV
    +8XTj44pJr+xHLNSV7RvDmDbt0Y71V0FVEM5PXiq5jb5vjv0dFgd7pewGvfKmSbq
    TyA47e+EDmeW06PEGw8gcyGr0S/7pBoLtlrieXiN+0ab4fUH20UzYkjke79f4YaO
    lrkYZSk2zUcF1yGLAVEivNC8xL5u3Id7uWhmHoQNyoYbOBHehdJ6DweJE5rRl1g5
    fEtHiCPAeG9JA7eZ6PruABQu+EBqtCa6TykEA7k1CB+dvKBqcdQbX9jJ0csxFSQM
    dFE8+A4mYm0kM4pYRTIEaMG8UTy5jCxawBz+EZQeMA7FROuOt7Ual2Wm7v+y3s7n
    R7laSk2rAgMBAAECggEADJbSIHBO2YPzEQtNFYlB382pVkQdBBXPDmdMRMspFt9v
    hyYp8/6SemKVaiddO3Se0E68yVWkNkLJeX+vjCQbim6ZvKsQKjgpDKcStCCzXupE
    tdqWqKJ4gFosYvLxZ8wKNnmpkZuEi2oUyU9ch+1ndlD+TfML2buWJm8zJMuMlpf3
    VzQ7IlzIhoFW2z+a2G/3y74jgXLr7yL9g2kdjTP2zofGA35ospjJXZ3iF9qYibUg
    OVdGuwPbBnbkj84FNqmvlgy6OjySuybnQ9X+7zpNrGwCzdSMQ3sbbh8ujVZp65SM
    +UbSMEEYtVldgHqHEZ1zhRhD4+geVVydv+BjgyThoQKBgQDKT2J1iCFrJhjaN4Ui
    J5SGUZrHHrFDhdukgHYDGKY4V+w1Q/sbeg+4sWDFf5zdgD9yCH3NdORqOk1esBXq
    CbUHP8sWJnVaVmNGLZlNi5b42PlTXoC0cHNOaTwlNreiBHcWLGNw0WOLkU/GrIsh
    5hGT7X+PhKMtXLv6yp+rRZMyuwKBgQDX1q0X4iyTyFECtXiAdphe2yI0Q7nb+gU7
    4OWhBylDL3aoP8In8/KqNrwCHat+ofdGvnDD3At1mRYng4FLD990ApIL44RmtQgB
    0hYyd5J3whMjTqaa1t04Rk1xQR3MWgab06imFYlOH6Jd6PxJM4zuEwMkuBMSqxV8
    SF2RhPL50QKBgEyM6TaLwglnKvQ3GdsomtyQOD6r8GsaVVfTe9QEGbEsI6asCHIH
    J7e89l8EwHhXtKoTaHa7ikpfsTLo8gHSlnsdulyxRKpgEcRWMLHU5dVXVFAlbBHa
    kubSjv2NzMIzalQri5z+venrnAIS+7ph8bjFnwTRLWVWt5JX5T7LXr1NAoGBAKkk
    RJU42zIcgs+aoooZZiK/mzhV8qqebceU4J6mXAGYimYjQOXKWFpndkI6OhCMoJlB
    2GDEaf6IL0Jb3dCS6cuh0A2dCD7skw/KMTbvWUqcPh8nHYyt4MKe5UVhgBaKXi9z
    WPB+ZBFi3Py2/i3nRgOzxnzZ+6hfhgDVPO4yv65hAoGAFYveoW1Jram4YXViTbqi
    OozkV5qkl8RkJtXkY/gd/KY415iXcze7X5Yy69pUvfCUKQj66OmUmDELeDry9DH/
    YuVNSmmt2mqSWfK6wYrHXHQnCNspSTASUm8zHC4ChckzGIEmlibquSAR2tVbzlR3
    /rtfeqaRNiBvOe6N55QMgLc=
    -----END PRIVATE KEY-----
