apiVersion: v1
kind: Service
metadata:
  name: namespacenodeselector
  namespace: default
spec:
  selector:
    app: namespacenodeselector
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
