apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: alpine
          command:
            - /bin/sh
            - -c
          args:
            - |
              hostname
              tail -f /dev/null
